-- AlterTable
ALTER TABLE "event" ALTER COLUMN "registrationstartdatetime" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "registrationenddatetime" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "eventstartdatetime" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "eventenddatetime" SET DEFAULT CURRENT_TIMESTAMP;
